server {
    listen 8080;
    server_name cvsickle.com;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /links.json {
        add_header Cache-Control "no-store";
    }

    location = /site.webmanifest {
        default_type application/manifest+json;
        add_header Cache-Control "public, max-age=86400";
    }

    gzip on;
    gzip_types text/css application/javascript application/json;
}