# Build and push Docker image on release
when:
  - event: release

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      depth: 0
      tags: true

steps:
  - name: build-and-push
    image: woodpeckerci/plugin-kaniko:latest
    settings:
      registry: git.cvsickle.com
      repo: git.cvsickle.com/cvsickle/profile
      username: cvsickle
      password:
        from_secret: forgejo_token
      tags:
        - latest
        - ${CI_COMMIT_TAG}
      build_args:
      - COMMIT_SHA=${CI_COMMIT_SHA}
      - COMMIT_AUTHOR_EMAIL=${CI_COMMIT_AUTHOR_EMAIL}
      dockerfile: Dockerfile
      context: .
